void _puts_recursion(char *s);
void _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _sqrt_recursive(int n, int i);
int is_prime_number(int n);
int is_prime(int n, int i);
int is_palindrome(char *s);
int _strlen(char *s);
int is_palin(int i, char *s, int n);
int wildcmp(char *s1, char *s2);
